# Site settings
title: SG Südtirol 07
header-img: img/home-bg.jpg
email: simonmulser@gmail.com
copyright_name: SG Südtirol 07
description: "Die offizielle Seite der Spielgemeinschaft Südtirol 07"
baseurl: ""
url: "http://simonmulser.github.io/"
github_username: ssimonmulser
facebook_username: sgsuedtirol

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
