# Site settings
title: SG Südtirol
header-img: img/tifosi-bg.jpg
email: simonmulser@gmail.com
copyright_name: Spielgemeinschaft Süditrol
description: "Die offizielle Seite der Spielgemeinschaft Südtirol"
baseurl: ""
url: "http://simonmulser.github.io/"
github_username: simonmulser
facebook_username: sgsuedtirol

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
